# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aoZvJnW07GcyK1eznkRHbwd4kcnsAMiI
"""

# main.py
import os
import re
import math
import shutil
import zipfile
import logging
import warnings
import numpy as np
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sentence_transformers import SentenceTransformer, CrossEncoder
from sklearn.metrics.pairwise import cosine_similarity

# إعدادات التسجيل والتنبيهات
warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger(__name__)

app = FastAPI(title="Graduation Project ATS AI API", version="1.0.0")

# تفعيل الـ CORS لتسهيل ربط موقع زملائك بالـ API دون قيود المتصفح
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# =========================================================
# CONFIGURATION & MODELS LOADING
# =========================================================
class Config:
    EMBEDDING_MODEL = "all-MiniLM-L6-v2"
    CROSS_ENCODER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"

    WEIGHTS = {
        "semantic": 0.35,
        "cross_encoder": 0.40,
        "skill": 0.15,
        "experience": 0.10
    }

    # القائمة الكاملة للمهارات والـ IDs الخاصة بك
    SKILL_ALIASES = {
        "python": ["python", "py"],
        "tensorflow": ["tensorflow", "tf"],
        "pytorch": ["pytorch"],
        "javascript": ["javascript", "js"],
        "react": ["react", "reactjs"],
        "machine learning": ["machine learning", "ml"],
        "deep learning": ["deep learning", "dl"],
        "nlp": ["nlp", "natural language processing"],
        "sql": ["sql"],
        "docker": ["docker"],
        "kubernetes": ["kubernetes", "k8s"],
        "aws": ["aws"],
        "linux": ["linux"],
        "git": ["git"],
        "cybersecurity": ["cybersecurity", "cyber security"],
        "devops": ["devops"],
        "api": ["api", "rest api"],
        "fastapi": ["fastapi"],
        "django": ["django"],
        "flask": ["flask"],
        "java": ["java"],
        "csharp": ["c#", ".net", "asp.net"],
        "html": ["html"],
        "css": ["css"],
        "nodejs": ["nodejs", "node.js"],
        "mongodb": ["mongodb"],
        "flutter": ["flutter"],
        "firebase": ["firebase"],
        "android": ["android"],
        "kotlin": ["kotlin"],
        "terraform": ["terraform"],
        "networking": ["networking"],
        "wireshark": ["wireshark"],
        "nmap": ["nmap"],
        "pentesting": ["pentesting"],
        "typescript": ["typescript", "ts"],
        "bootstrap": ["bootstrap"],
        "tailwind css": ["tailwind css", "tailwind"],
        "sass": ["sass"],
        "less": ["less"],
        "angular": ["angular", "angularjs"],
        "vue.js": ["vue.js", "vue", "vuejs"],
        "next.js": ["next.js", "nextjs"],
        "nuxt.js": ["nuxt.js", "nuxtjs"],
        "svelte": ["svelte"],
        "blazor": ["blazor"],
        "jquery": ["jquery"],
        "web components": ["web components"],
        "c": ["c language"],
        "c++": ["c++", "cpp"],
        "php": ["php"],
        "ruby": ["ruby"],
        "go": ["golang", "go language"],
        "rust": ["rust"],
        "swift": ["swift"],
        "dart": ["dart"],
        "scala": ["scala"],
        "r": ["r language", "r programming"],
        "matlab": ["matlab"],
        "perl": ["perl"],
        "lua": ["lua"],
        "groovy": ["groovy"],
        "f#": ["f#", "fsharp"],
        "vb.net": ["vb.net", "visual basic"],
        "asp.net core": ["asp.net core"],
        "asp.net mvc": ["asp.net mvc"],
        "razor pages": ["razor pages"],
        "blazor server": ["blazor server"],
        "blazor webassembly": ["blazor webassembly", "blazor wasm"],
        "entity framework core": ["entity framework core", "ef core"],
        "dapper": ["dapper"],
        "linq": ["linq"],
        "ado.net": ["ado.net"],
        "minimal apis": ["minimal apis"],
        "signalr": ["signalr"],
        "wpf": ["wpf"],
        "windows forms": ["windows forms", "winforms"],
        ".net maui": [".net maui", "maui"],
        "xamarin": ["xamarin"],
        "express.js": ["express.js", "express", "expressjs"],
        "nestjs": ["nestjs", "nest.js"],
        "fastify": ["fastify"],
        "koa.js": ["koa.js", "koa"],
        "spring boot": ["spring boot"],
        "spring mvc": ["spring mvc"],
        "spring security": ["spring security"],
        "hibernate": ["hibernate"],
        "jakarta ee": ["jakarta ee", "java ee"],
        "laravel": ["laravel"],
        "symfony": ["symfony"],
        "codeigniter": ["codeigniter"],
        "ruby on rails": ["ruby on rails", "rails"],
        "gin": ["gin"],
        "fiber": ["fiber"],
        "rest api": ["rest api", "restful"],
        "graphql": ["graphql"],
        "grpc": ["grpc"],
        "soap": ["soap"],
        "web api": ["web api"],
        "microservices": ["microservices"],
        "monolithic architecture": ["monolithic architecture", "monolithic"],
        "clean architecture": ["clean architecture"],
        "onion architecture": ["onion architecture"],
        "hexagonal architecture": ["hexagonal architecture"],
        "domain-driven design": ["domain-driven design", "ddd"],
        "cqrs": ["cqrs"],
        "event-driven architecture": ["event-driven architecture", "event driven"],
        "message queues": ["message queues", "message queue", "rabbitmq", "kafka"],
        "mediatr": ["mediatr"],
        "repository pattern": ["repository pattern"],
        "unit of work pattern": ["unit of work"],
        "design patterns": ["design patterns"],
        "solid principles": ["solid principles", "solid"],
        "object-oriented programming": ["object-oriented programming", "oop"],
        "functional programming": ["functional programming"],
        "data structures": ["data structures"],
        "algorithms": ["algorithms"],
        "system design": ["system design"],
        "software architecture": ["software architecture"],
        "t-sql": ["t-sql", "tsql"],
        "pl/sql": ["pl/sql", "plsql"],
        "microsoft sql server": ["microsoft sql server", "sql server", "mssql"],
        "mysql": ["mysql"],
        "postgresql": ["postgresql", "postgres"],
        "oracle database": ["oracle database", "oracle"],
        "sqlite": ["sqlite"],
        "mariadb": ["mariadb"],
        "redis": ["redis"],
        "firebase firestore": ["firebase firestore", "firestore"],
        "firebase realtime database": ["firebase realtime database"],
        "elasticsearch": ["elasticsearch"],
        "opensearch": ["opensearch"],
        "dynamodb": ["dynamodb"],
        "cassandra": ["cassandra"],
        "neo4j": ["neo4j"],
        "couchbase": ["couchbase"],
        "influxdb": ["influxdb"],
        "database design": ["database design"],
        "database normalization": ["database normalization"],
        "stored procedures": ["stored procedures"],
        "database indexing": ["database indexing"],
        "query optimization": ["query optimization"],
        "database administration": ["database administration", "dba"],
        "database backup and recovery": ["database backup and recovery"],
        "data modeling": ["data modeling"],
        "nosql databases": ["nosql"],
        "relational databases": ["relational databases", "rdbms"],
        "github": ["github"],
        "gitlab": ["gitlab"],
        "bitbucket": ["bitbucket"],
        "azure devops": ["azure devops"],
        "jira": ["jira"],
        "trello": ["trello"],
        "confluence": ["confluence"],
        "agile": ["agile"],
        "scrum": ["scrum"],
        "kanban": ["kanban"],
        "sdlc": ["sdlc"],
        "code review": ["code review"],
        "pair programming": ["pair programming"],
        "technical documentation": ["technical documentation"],
        "software estimation": ["software estimation"],
        "helm": ["helm"],
        "nginx": ["nginx"],
        "apache http server": ["apache http server", "apache"],
        "iis": ["iis"],
        "ubuntu": ["ubuntu"],
        "debian": ["debian"],
        "red hat enterprise linux": ["red hat", "rhel"],
        "windows server": ["windows server"],
        "bash scripting": ["bash scripting", "bash"],
        "powershell": ["powershell"],
        "shell scripting": ["shell scripting"],
        "system administration": ["system administration", "sysadmin"],
        "virtualization": ["virtualization"],
        "vmware": ["vmware"],
        "hyper-v": ["hyper-v"],
        "microsoft azure": ["microsoft azure", "azure"],
        "google cloud platform": ["google cloud platform", "gcp"],
        "cloud computing": ["cloud computing"],
        "serverless computing": ["serverless computing", "serverless"],
        "aws lambda": ["aws lambda", "lambda"],
        "azure functions": ["azure functions"],
        "google cloud functions": ["google cloud functions"],
        "azure app service": ["azure app service"],
        "azure sql database": ["azure sql database"],
        "azure storage": ["azure storage"],
        "amazon s3": ["amazon s3", "s3"],
        "amazon ec2": ["amazon ec2", "ec2"],
    }

    SKILL_ALIAS_KEY_TO_ID = {
        "python": 177, "javascript": 178, "react": 186, "java": 176, "csharp": 175, "html": 180, "css": 181,
        "nodejs": 227, "mongodb": 280, "kotlin": 201, "django": 237, "flask": 238, "fastapi": 239, "sql": 271,
        "git": 301, "docker": 317, "kubernetes": 318, "aws": 335, "linux": 323, "firebase": 282, "networking": 48,
        "cybersecurity": 31, "devops": 30, "api": 25, "tensorflow": 373, "pytorch": 374, "machine learning": 375,
        "deep learning": 376, "nlp": 377, "flutter": 378, "android": 379, "terraform": 380, "wireshark": 381,
        "nmap": 382, "pentesting": 383, "typescript": 179, "bootstrap": 182, "tailwind css": 183, "sass": 184,
        "less": 185, "angular": 187, "vue.js": 188, "next.js": 189, "nuxt.js": 190, "svelte": 191, "blazor": 192,
        "jquery": 193, "web components": 194, "c": 195, "c++": 196, "php": 197, "ruby": 198, "go": 199, "rust": 200,
        "swift": 202, "dart": 203, "scala": 204, "r": 205, "matlab": 206, "perl": 207, "lua": 208, "groovy": 209,
        "f#": 210, "vb.net": 211, "asp.net core": 212, "asp.net mvc": 213, "razor pages": 214, "blazor server": 215,
        "blazor webassembly": 216, "entity framework core": 217, "dapper": 218, "linq": 219, "ado.net": 220,
        "minimal apis": 221, "signalr": 222, "wpf": 223, "windows forms": 224, ".net maui": 225, "xamarin": 226,
        "express.js": 228, "nestjs": 229, "fastify": 230, "koa.js": 231, "spring boot": 232, "spring mvc": 233,
        "spring security": 234, "hibernate": 235, "jakarta ee": 236, "laravel": 240, "symfony": 241, "codeigniter": 242,
        "ruby on rails": 243, "gin": 244, "fiber": 245, "rest api": 246, "graphql": 247, "grpc": 248, "soap": 249,
        "web api": 250, "microservices": 251, "monolithic architecture": 252, "clean architecture": 253,
        "onion architecture": 254, "hexagonal architecture": 255, "domain-driven design": 256, "cqrs": 257,
        "event-driven architecture": 258, "message queues": 259, "mediatr": 260, "repository pattern": 261,
        "unit of work pattern": 262, "design patterns": 263, "solid principles": 264, "object-oriented programming": 265,
        "functional programming": 266, "data structures": 267, "algorithms": 268, "system design": 269,
        "software architecture": 270, "t-sql": 272, "pl/sql": 273, "microsoft sql server": 274, "mysql": 275,
        "postgresql": 276, "oracle database": 277, "sqlite": 278, "mariadb": 279, "mongodb": 280, "redis": 281,
        "firebase firestore": 282, "firebase realtime database": 283, "elasticsearch": 284, "opensearch": 285,
        "dynamodb": 286, "cassandra": 287, "neo4j": 288, "couchbase": 289, "influxdb": 290, "database design": 291,
        "database normalization": 292, "stored procedures": 293, "database indexing": 294, "query optimization": 295,
        "database administration": 296, "database backup and recovery": 297, "data modeling": 298, "nosql databases": 299,
        "relational databases": 300, "github": 302, "gitlab": 303, "bitbucket": 304, "azure devops": 305, "jira": 306,
        "trello": 307, "confluence": 308, "agile": 309, "scrum": 310, "kanban": 311, "sdlc": 312, "code review": 313,
        "pair programming": 314, "technical documentation": 315, "software estimation": 316, "helm": 319, "nginx": 320,
        "apache http server": 321, "iis": 322, "ubuntu": 324, "debian": 325, "red hat enterprise linux": 326,
        "windows server": 327, "bash scripting": 328, "powershell": 329, "shell scripting": 330, "system administration": 331,
        "virtualization": 332, "vmware": 333, "hyper-v": 334, "microsoft azure": 336, "google cloud platform": 337,
        "cloud computing": 338, "serverless computing": 339, "aws lambda": 340, "azure functions": 341,
        "google cloud functions": 342, "azure app service": 343, "azure sql database": 344, "azure storage": 345,
        "amazon s3": 346, "amazon ec2": 347
    }

# تحميل نماذج الذكاء الاصطناعي في ذاكرة السيرفر عند الإقلاع
logger.info("Initializing NLP models globally...")
embedder = SentenceTransformer(Config.EMBEDDING_MODEL)
cross_encoder = CrossEncoder(Config.CROSS_ENCODER_MODEL)
logger.info("Global models loaded completely.")

# =========================================================
# HELPER FUNCTIONS
# =========================================================
def parse_date_safely(text_context):
    months_map = {
        "jan": "01", "feb": "02", "mar": "03", "apr": "04", "may": "05", "jun": "06",
        "jul": "07", "aug": "08", "sep": "09", "oct": "10", "nov": "11", "dec": "12"
    }
    numeric_range = re.findall(r"\b(0[1-9]|1[0-2])[-/](20\d{2}|19\d{2})\b", text_context)
    if numeric_range:
        return f"{numeric_range[0][1]}-{numeric_range[0][0]}-01"
    for month_name, month_num in months_map.items():
        if re.search(rf"\b{month_name}\b", text_context, re.IGNORECASE):
            year_match = re.search(r"\b(20\d{2}|19\d{2})\b", text_context)
            if year_match:
                return f"{year_match.group(1)}-{month_num}-01"
    year_only = re.search(r"\b(20\d{2}|19\d{2})\b", text_context)
    if year_only:
        return f"{year_only.group(1)}-01-01"
    return None

def clean_extracted_name(name, strip_words):
    if not name: return "Not Found"
    name = re.sub(r"[:\-,\.\(\)\t]", " ", name)
    for word in strip_words:
        name = re.sub(rf"\b{word}\b", "", name, flags=re.IGNORECASE)
    name = re.sub(r"\s+", " ", name).strip()
    return name if len(name) > 2 else "Not Found"

# =========================================================
# EXTRACTION CORE
# =========================================================
class Extractor:
    def __init__(self):
        self.skill_patterns = {
            skill: [
                re.compile(rf"(?<![a-zA-Z0-9]){re.escape(alias)}(?![a-zA-Z0-9])", re.IGNORECASE)
                for alias in aliases
            ]
            for skill, aliases in Config.SKILL_ALIASES.items()
        }

    def extract_skills(self, text):
        found_skill_ids = set()
        for skill, patterns in self.skill_patterns.items():
            if any(pattern.search(text) for pattern in patterns):
                skill_id = Config.SKILL_ALIAS_KEY_TO_ID.get(skill.lower())
                if skill_id is not None:
                    found_skill_ids.add(skill_id)
        return sorted(list(found_skill_ids))

    def extract_years(self, text):
        lower_text = text.lower()
        years_found = []
        patterns = [
            r"(\d{1,2})\+?\s*(?:years|yrs)\s+(?:of\s+)?experience",
            r"experience\s*(?:of|in)?\s*(\d{1,2})\+?\s*(?:years|yrs)?"
        ]
        for pattern in patterns:
            for x in re.findall(pattern, lower_text):
                value = int(x)
                if 0 <= value <= 40:
                    years_found.append(value)
        return max(years_found) if years_found else 0

def extract_education_info(text):
    education_list = []
    seen_universities = set()

    degree_levels = [
        {"level": "PhD", "patterns": [r"\b(ph\.?d\.?|doctorate|doctor of philosophy)\b"]},
        {"level": "Master", "patterns": [r"\b(master(?:'s)?(?:\s+degree)?)\b"]},
        {"level": "Bachelor", "patterns": [r"\b(bachelor(?:'s)?(?:\s+degree)?)\b"]}
    ]
    university_patterns = [
        r"\b(University\s+of\s+[A-Z][A-Za-z&.\s]{2,40})\b",
        r"\b([A-Z][A-Za-z&.\s]{2,40}\sUniversity)\b",
        r"\b([A-Z][A-Za-z&.\s]{2,40}\sCollege)\b"
    ]
    gpa_patterns = [
        r"\b(?:gpa|cgpa|grade|g\.p\.a)\s*[:\-]?\s*([0-4]\.\d{1,3}|4\.0|[5-9]\d(?:\.\d{1,2})?%?)\b",
        r"\b([0-3]\.\d{1,2}|4\.0)\s*/\s*4\b"
    ]

    lines = text.split('\n')
    for i, line in enumerate(lines):
        if any(k in line.lower() for k in ["education", "university", "bachelor", "master", "bsc", "degree", "college"]):
            inst_name = None
            deg_name = None
            gpa_val = None
            from_d = None
            to_d = None

            context = line + " " + (lines[i+1] if i+1 < len(lines) else "")
            for pat in university_patterns:
                m = re.search(pat, context)
                if m: inst_name = m.group(1).strip(); break

            if inst_name:
                inst_name = clean_extracted_name(inst_name, ["From", "To", "Date", "GPA"])
                if inst_name.lower() in seen_universities or inst_name == "Not Found": continue

            for group in degree_levels:
                for pat in group["patterns"]:
                    m = re.search(pat, context, re.IGNORECASE)
                    if m: deg_name = group["level"]; break
                if deg_name: break

            for pat in gpa_patterns:
                m = re.search(pat, context, re.IGNORECASE)
                if m: gpa_val = m.group(1).strip(); break

            years = re.findall(r"\b(20\d{2}|19\d{2})\b", context)
            if len(years) >= 2:
                from_d = f"{years[0]}-01-01"
                to_d = f"{years[1]}-01-01"
            elif len(years) == 1:
                to_d = f"{years[0]}-01-01"

            if inst_name and inst_name != "Not Found":
                seen_universities.add(inst_name.lower())
                education_list.append({
                    "institutionName": inst_name,
                    "fromDate": from_d,
                    "toDate": to_d,
                    "degree": deg_name if deg_name else "Bachelor",
                    "gpa": gpa_val if gpa_val else None
                })
    return education_list

def extract_experience_info(text, extractor_instance):
    experience_list = []
    seen_companies = set()

    company_patterns = [
        r"\b([A-Z][A-Za-z0-9\s&.,]{2,30}\s(?:Ltd|Inc|Corp|Company|Solutions|Bank|Center|Institute|Group|Technologies|Software))\b",
        r"(?:Company|Employer)\s*[:\-]\s*([A-Za-z0-9\s&.,]{2,30})"
    ]

    blocks = text.split('\n')
    for i, line in enumerate(blocks):
        if any(keyword in line.lower() for keyword in ["engineer", "developer", "analyst", "manager", "intern"]):
            comp_name = "Not Found"
            from_d = None
            to_d = None
            job_title = line.strip()[:60]

            context_text = line + " " + (blocks[i+1] if i+1 < len(blocks) else "")
            for pat in company_patterns:
                m = re.search(pat, context_text, re.IGNORECASE)
                if m: comp_name = m.group(1).strip(); break

            if comp_name:
                comp_name = clean_extracted_name(comp_name, ["Experience", "Responsibilities", "Using", "Present"])
                if comp_name.lower() in seen_companies or comp_name == "Not Found": continue

            date_range = re.search(r"\b(20\d{2}|19\d{2})\s*[-–—]\s*(20\d{2}|19\d{2}|present|current|now)\b", context_text, re.IGNORECASE)
            if date_range:
                from_d = f"{date_range.group(1)}-01-01"
                to_d = "2026-01-01" if any(w in date_range.group(2).lower() for w in ["present", "current", "now"]) else f"{date_range.group(2)}-01-01"
            else:
                from_d = parse_date_safely(context_text)

            job_skills = extractor_instance.extract_skills(context_text)

            if comp_name != "Not Found":
                seen_companies.add(comp_name.lower())
                experience_list.append({
                    "companyName": comp_name,
                    "fromDate": from_d,
                    "toDate": to_d,
                    "jobTitle": job_title,
                    "description": context_text.strip()[:150] + "...",
                    "skills": job_skills
                })
    return experience_list[:5]

# =========================================================
# WEB API ENDPOINT
# =========================================================
@app.post("/api/v1/screen-cvs")
async def screen_cvs_endpoint(
    roleName: str = Form(...),
    jobDesc: str = Form(...),
    file: UploadFile = File(...)
):
    if not file.filename.lower().endswith(".zip"):
        raise HTTPException(status_code=400, detail="Only compressed .zip files are allowed.")

    temp_zip_dir = "./temp_zip_storage"
    extracted_cv_dir = f"./cvs_{int(random.randint(1000, 9999))}"
    os.makedirs(temp_zip_dir, exist_ok=True)
    os.makedirs(extracted_cv_dir, exist_ok=True)

    zip_file_path = os.path.join(temp_zip_dir, file.filename)

    try:
        # 1. حفظ ملف الـ Zip مؤقتاً
        with open(zip_file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        # 2. فك ضغط ملف السير الذاتية
        with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
            zip_ref.extractall(extracted_cv_dir)

        # 3. معالجة وتصنيف الملفات المفكوكة
        extractor = Extractor()
        api_results = []

        for root, dirs, files_list in os.walk(extracted_cv_dir):
            for cv_file in files_list:
                cv_path = os.path.join(root, cv_file)

                # قراءة محتوى السيرة الذاتية (PDF, Docx, Txt)
                text = ""
                try:
                    if cv_file.lower().endswith(".pdf"):
                        reader = PdfReader(cv_path)
                        text = "\n".join([page.extract_text() or "" for page in reader.pages])
                    elif cv_file.lower().endswith(".docx"):
                        doc = docx.Document(cv_path)
                        text = "\n".join([p.text for p in doc.paragraphs if p.text.strip()])
                    elif cv_file.lower().endswith(".txt"):
                        with open(cv_path, "r", encoding="utf-8", errors="ignore") as f:
                            text = f.read()
                except Exception as read_err:
                    logger.error(f"Error reading {cv_file}: {read_err}")
                    continue

                text = str(text)
                text = re.sub(r"[ \t]+", " ", text)
                text = re.sub(r"\n\s*\n+", "\n", text).strip()
                if not text: continue

                # استخراج حقول البيانات الفردية
                skills = extractor.extract_skills(text)
                years = extractor.extract_years(text)
                education_summary = extract_education_info(text)
                experience_summary = extract_experience_info(text, extractor)

                linkedin_match = re.search(r"(https?:\/\/)?(www\.)?linkedin\.com\/in\/[A-Za-z0-9_-]+", text, re.IGNORECASE)
                linkedin_url = linkedin_match.group(0) if linkedin_match else None

                # حساب درجات التطابق باستخدام النماذج المسبقة التحميل
                cv_emb = embedder.encode([text.lower()])
                job_emb = embedder.encode([jobDesc.lower()])
                semantic_score = float(cosine_similarity(cv_emb, job_emb)[0][0])
                semantic_score = max(0.0, semantic_score)

                cross_logit = cross_encoder.predict([(text.lower(), jobDesc.lower())])[0]
                ml_score = 1 / (1 + math.exp(-float(cross_logit))) # Sigmoid function

                job_skills_set = set(extractor.extract_skills(jobDesc))
                cv_skills_set = set(skills)
                matched_skill_ids = sorted(list(cv_skills_set & job_skills_set))
                missing_skill_ids = sorted(list(job_skills_set - cv_skills_set))

                skill_score = len(matched_skill_ids) / len(job_skills_set) if job_skills_set else 0.0
                exp_score = min(years / 10.0, 1.0)

                final_score = (
                    semantic_score * Config.WEIGHTS["semantic"] +
                    ml_score * Config.WEIGHTS["cross_encoder"] +
                    skill_score * Config.WEIGHTS["skill"] +
                    exp_score * Config.WEIGHTS["experience"]
                )

                ai_explanation = (
                    f"Candidate matches {len(matched_skill_ids)} specific skills from the job description. "
                    f"The semantic match score is {semantic_score*100:.1f}%. "
                    f"Extracted experience level is {years} years."
                )

                dto = {
                    "applicationId": int(hash(cv_file) % 1000000),
                    "finalScore": round(final_score, 4),
                    "mlScore": round(ml_score, 4),
                    "semanticScore": round(semantic_score, 4),
                    "aiExplanation": ai_explanation,
                    "linkedInUrl": linkedin_url,
                    "position": roleName,
                    "resubmissionRequired": bool(final_score < 0.45),
                    "matchingSkills": [int(x) for x in matched_skill_ids],
                    "missingSkills": [int(x) for x in missing_skill_ids],
                    "experienceSummary": experience_summary,
                    "educationSummary": education_summary
                }
                api_results.append(dto)

        # ترتيب النتائج من الأعلى تقييماً إلى الأقل
        api_results = sorted(api_results, key=lambda x: x["finalScore"], reverse=True)
        return api_results

    except Exception as server_err:
        logger.error(f"Internal API Error: {server_err}")
        raise HTTPException(status_code=500, detail=str(server_err))

    finally:
        # تنظيف مساحة السيرفر وحذف المجلدات المؤقتة بعد انتهاء الطلب
        if os.path.exists(zip_file_path): os.remove(zip_file_path)
        if os.path.exists(extracted_cv_dir): shutil.rmtree(extracted_cv_dir)